export { frame } from './types.ts';
export type {
  Delta3,
  Dir3,
  FrameTag,
  LinearMat4,
  Mat4,
  Point3,
  ProjectionMat4,
  Quaternion,
} from './types.ts';

export {
  addPoint3,
  addVec3,
  angleBetweenVec3,
  angleBetweenVec3Unsafe,
  crossVec3,
  delta3,
  dir3,
  distancePoint3,
  distanceVec3,
  dotVec3,
  lengthSquaredVec3,
  lengthVec3,
  lerpVec3,
  negVec3,
  normalizeVec3,
  normalizeVec3Unsafe,
  point3,
  projectVec3,
  projectVec3Unsafe,
  reflectVec3,
  reflectVec3Unsafe,
  scaleDir3,
  scaleVec3,
  subPoint3,
  subPoint3Delta3,
  subVec3,
  zeroVec3,
} from './vector3.ts';

export {
  composeQuats,
  type EulerOrder,
  quat,
  quatConjugate,
  quatFromAxisAngle,
  quatFromAxisAngleUnsafe,
  quatFromEuler,
  quatFromEulerUnsafe,
  quatIdentity,
  quatInverse,
  quatInverseUnsafe,
  quatNlerp,
  quatNlerpUnsafe,
  quatNorm,
  quatNormalize,
  quatNormalizeUnsafe,
  quatNormSquared,
  quatSlerp,
  quatSlerpUnsafe,
  rotateVec3ByQuat,
  rotateVec3ByQuatUnsafe,
} from './quaternion.ts';

export {
  composeMat4,
  createTrsMat4Cache,
  invertRigidMat4,
  invertRigidMat4Unsafe,
  mat4,
  mat4FromQuaternion,
  mat4FromQuaternionUnsafe,
  mat4FromRigidTransform,
  mat4FromScale,
  mat4FromTranslation,
  mat4FromTRS,
  mat4FromTRSUnsafe,
  mat4Identity,
  mat4LookAt,
  mat4LookAtUnsafe,
  mat4Ortho,
  mat4OrthoUnsafe,
  mat4Perspective,
  mat4PerspectiveUnsafe,
  mat4Unsafe,
  normalMatrixFromMat4,
  normalMatrixFromMat4Unsafe,
  projectPoint3,
  projectPoint3Unsafe,
  transformDirection3,
  transformPoint3,
  transposeMat4,
} from './matrix4.ts';
