export { frame } from './types.ts';
export type {
  Delta3,
  Dir3,
  FrameTag,
  LinearMat4,
  Mat4,
  Point3,
  ProjectionMat4,
  Quaternion,
} from './types.ts';

export {
  addPoint3,
  addVec3,
  angleBetweenVec3,
  crossVec3,
  delta3,
  dir3,
  distancePoint3,
  distanceVec3,
  dotVec3,
  lengthSquaredVec3,
  lengthVec3,
  lerpVec3,
  negVec3,
  normalizeVec3,
  point3,
  projectVec3,
  reflectVec3,
  scaleDir3,
  scaleVec3,
  subPoint3,
  subPoint3Delta3,
  subVec3,
  zeroVec3,
} from './vector3.ts';

export {
  composeQuats,
  type EulerOrder,
  quat,
  quatConjugate,
  quatFromAxisAngle,
  quatFromEuler,
  quatIdentity,
  quatInverse,
  quatNlerp,
  quatNorm,
  quatNormalize,
  quatNormSquared,
  quatSlerp,
  rotateVec3ByQuat,
} from './quaternion.ts';

export {
  composeMat4,
  createTrsMat4Cache,
  invertRigidMat4,
  mat4,
  mat4FromQuaternion,
  mat4FromRigidTransform,
  mat4FromScale,
  mat4FromTranslation,
  mat4FromTRS,
  mat4Identity,
  mat4LookAt,
  mat4Perspective,
  normalMatrixFromMat4,
  projectPoint3,
  transformDirection3,
  transformPoint3,
  transposeMat4,
} from './matrix4.ts';
